// src/vue/ArcanaDataTable.vue
<script setup lang="ts">
import { computed, defineComponent, h, onBeforeUnmount, onMounted, ref, shallowRef, watch } from "vue";
import { createDataTable } from "../core/controller";
import { formatMessage, resolveArcanaLocale, resolveArcanaMessages } from "../core/locale";
import { arcanaThemeClass } from "../core/theme";
import { actionStyle, alignmentClass, columnStyle, expandedRowLoadingContent, expanderStyle, pagination, selectionStyle } from "../core/view";
import type { DataTableApi, DataTableColumn, DataTableConfig, DataTableRow, Renderable } from "../core/types";
import FilterField from "./FilterField.vue";
import "../assets/SparkGrid.css";

const props = defineProps<{ config: DataTableConfig<DataTableRow> }>();
const emit = defineEmits<{ mounted: [grid: DataTableApi<DataTableRow>] }>();
const grid = shallowRef(createDataTable(props.config));
const revision = shallowRef(0);
const menu = ref<{ x: number; y: number; items: import("../core/types").ContextMenuItem[] } | null>(null);
const sortMenu = ref<{ x: number; y: number; name: string } | null>(null);
const focusedRow = ref<string | null>(null);
const focusedCell = ref<string | null>(null);
let unsubscribe = grid.value.subscribe(() => { revision.value += 1; });

watch(() => props.config, (config) => {
  unsubscribe();
  grid.value = createDataTable(config);
  unsubscribe = grid.value.subscribe(() => { revision.value += 1; });
  if (config.sendRequestOnMounted !== false) void grid.value.refresh();
});

const closeMenus = () => { menu.value = null; sortMenu.value = null; };
const onWindowKey = (event: KeyboardEvent) => { if (event.key === "Escape") closeMenus(); };
onMounted(() => {
  emit("mounted", grid.value);
  if (props.config.sendRequestOnMounted !== false) void grid.value.refresh();
  window.addEventListener("click", closeMenus);
  window.addEventListener("blur", closeMenus);
  window.addEventListener("keydown", onWindowKey);
});
onBeforeUnmount(() => {
  unsubscribe();
  window.removeEventListener("click", closeMenus);
  window.removeEventListener("blur", closeMenus);
  window.removeEventListener("keydown", onWindowKey);
});

defineExpose({
  get api() { return grid.value; },
  refresh: () => grid.value.refresh(), fetch: () => grid.value.fetch(), setRows: (rows: DataTableRow[]) => grid.value.setRows(rows),
  setDataset: (rows: DataTableRow[]) => grid.value.setDataset(rows), getDataset: () => grid.value.getDataset(),
  clearRows: () => grid.value.clearRows(), addRow: (row: DataTableRow) => grid.value.addRow(row),
  removeRow: (uuid: string) => grid.value.removeRow(uuid), updateRow: (uuid: string, row: Partial<DataTableRow>) => grid.value.updateRow(uuid, row),
  upsert: (uuid: string, row: DataTableRow) => grid.value.upsert(uuid, row), getRows: () => grid.value.getRows(),
  getCheckedRows: () => grid.value.getCheckedRows(), clearCheckedRows: () => grid.value.clearCheckedRows(),
  setFilter: (name: string, value: unknown) => grid.value.setFilter(name, value), setFilters: (filters: Record<string, unknown>) => grid.value.setFilters(filters),
  expandRow: (uuid: string) => grid.value.expandRow(uuid), collapseRow: (uuid: string) => grid.value.collapseRow(uuid),
  getExpandedRows: () => grid.value.getExpandedRows()
});

const themeClass = computed(() => arcanaThemeClass(props.config.theme));
const msg = computed(() => resolveArcanaMessages(props.config));
const gridLocale = computed(() => resolveArcanaLocale(props.config));
const state = computed(() => { revision.value; return grid.value.getSnapshot(); });
const columns = computed(() => { revision.value; return grid.value.getColumns(); });
const pages = computed(() => pagination(state.value.currentPage, state.value.totalRows, state.value.rowsPerPage));
const lastPage = computed(() => Math.ceil(state.value.totalRows / state.value.rowsPerPage));
const beginning = computed(() => state.value.totalRows ? ((state.value.currentPage - 1) * state.value.rowsPerPage) + 1 : 0);
const ending = computed(() => Math.min(state.value.currentPage * state.value.rowsPerPage, state.value.totalRows));
const searchable = (column: DataTableColumn<DataTableRow>) => props.config.searchEnabled !== false && (column.searchEnabled ?? true);
const disabledFilter = (column: DataTableColumn<DataTableRow>) => Boolean(props.config.disableFilterWhenPresentOnInitialFilters && props.config.initialFilters?.[column.filterName ?? column.name]);
const openSortMenu = (event: MouseEvent, column: DataTableColumn<DataTableRow>) => {
  if (props.config.orderByEnabled === false || column.orderByEnabled === false) return;
  const name = column.filterName ?? column.name;
  event.stopPropagation();
  const rect = (event.currentTarget as HTMLElement).getBoundingClientRect();
  sortMenu.value = sortMenu.value?.name === name ? null : { x: rect.left, y: rect.bottom + 2, name };
};
const applySortOption = (direction: "asc" | "desc" | null) => {
  if (!sortMenu.value) return;
  void grid.value.applyOrderBy(direction ? { name: sortMenu.value.name, direction } : null);
  sortMenu.value = null;
};
const sortMark = (column: DataTableColumn<DataTableRow>) => state.value.orderBy?.name !== (column.filterName ?? column.name) ? "↕" : state.value.orderBy.direction === "asc" ? "↑" : "↓";
const headerValue = (column: DataTableColumn<DataTableRow>) => column.headerContentGetter?.(props.config.onBeforeHeaderCellMounted?.(column, grid.value), grid.value) ?? props.config.onBeforeHeaderCellMounted?.(column, grid.value) ?? column.label;
const cellStyle = (column: DataTableColumn<DataTableRow>, row: DataTableRow) => ({ ...columnStyle(column, grid.value), padding: "8px 10px", ...props.config.onBeforeCellStyleMounted?.(grid.value.getCellValue(column, row), column, row, grid.value), ...column.onBeforeColumnStyleMounted?.(grid.value.getCellValue(column, row), row, grid.value) });
const selectRadio = (row: DataTableRow) => grid.value.setSelectedRadioRow(row);
const expandable = computed(() => Boolean(props.config.expandableRowsEnabled));
const isExpanded = (row: DataTableRow) => Boolean(row._uuid && state.value.expandedRowUuids.includes(row._uuid));
const toggleExpand = (row: DataTableRow) => {
  if (!row._uuid) return;
  isExpanded(row) ? grid.value.collapseRow(row._uuid) : grid.value.expandRow(row._uuid);
};
const onExpandToggle = (event: MouseEvent, row: DataTableRow) => {
  event.stopPropagation();
  toggleExpand(row);
};
const onRow = (row: DataTableRow) => {
  if (props.config.rowFocusEnabled) focusedRow.value = row._uuid ?? null;
  if (expandable.value && props.config.expandRowOnClick) toggleExpand(row);
  props.config.onClickRow?.(row, grid.value);
};
const onCell = (column: DataTableColumn<DataTableRow>, row: DataTableRow) => {
  if (props.config.cellFocusEnabled ?? true) focusedCell.value = `${row._uuid}:${column.name}`;
  props.config.onClickCell?.(grid.value.getCellValue(column, row), column, row, grid.value);
};
const selectionCellStyle = (row: DataTableRow) => ({ ...selectionStyle, ...props.config.onBeforeCheckboxAndRadioButtonStyleMounted?.(row, grid.value) });
const context = (event: MouseEvent, column: DataTableColumn<DataTableRow>, row: DataTableRow) => {
  const items = props.config.onContextMenu?.(grid.value.getCellValue(column, row), column, row, grid.value);
  if (items?.length) { event.preventDefault(); menu.value = { x: event.clientX, y: event.clientY, items }; }
};
const RuntimeContent = defineComponent({ props: { value: null }, setup(runtimeProps) { return () => {
  const value = typeof runtimeProps.value === "function" ? (runtimeProps.value as () => unknown)() : runtimeProps.value;
  if (value == null) return null;
  if (typeof value === "string") return h("span", { innerHTML: value });
  if (typeof value === "number" || typeof value === "boolean") return h("span", String(value));
  return value as never;
}; }});
const ExpandedRowContent = defineComponent({ props: { row: null }, setup(detailProps) {
  const detail = ref<{ status: "loading" | "ready" | "error"; content?: Renderable }>({ status: "loading" });
  let active = true;
  let generation = 0;
  const resolve = (row: DataTableRow) => {
    const current = ++generation;
    detail.value = { status: "loading" };
    try {
      const result = props.config.expandedRowRenderer?.(row, grid.value);
      if (result && typeof (result as Promise<Renderable>).then === "function") {
        (result as Promise<Renderable>).then(
          (content) => { if (active && current === generation) detail.value = { status: "ready", content }; },
          (error) => { console.error(error); if (active && current === generation) detail.value = { status: "error" }; }
        );
      } else {
        detail.value = { status: "ready", content: result };
      }
    } catch (error) {
      console.error(error);
      detail.value = { status: "error" };
    }
  };
  resolve(detailProps.row as DataTableRow);
  watch(() => detailProps.row, (row) => resolve(row as DataTableRow));
  onBeforeUnmount(() => { active = false; });
  return () => {
    if (detail.value.status === "loading") return h(RuntimeContent, { value: props.config.expandedRowLoadingRenderer?.(detailProps.row as DataTableRow, grid.value) ?? expandedRowLoadingContent(msg.value) });
    if (detail.value.status === "error") return h("div", { class: "grid-detail-error" }, msg.value.expandedError);
    return h(RuntimeContent, { value: detail.value.content });
  };
}});
</script>

<template>
  <div class="spark-grid grid-wrapper" :class="[themeClass, { 'spark-grid-responsive-vertical': config.responsiveMode === 'VERTICAL_RECORD' }]" :aria-label="config.ariaLabel ?? msg.gridLabel" :aria-busy="state.loading">
    <div v-if="state.error" class="arcana-grid-error" role="alert">{{ msg.loadError }}</div>
    <div class="spark-grid-body" :style="config.overflowEnabled ? { maxHeight: `${config.height ?? 560}px`, overflow: 'auto' } : undefined">
      <div class="grid-header" :class="{ 'grid-header-sticky': config.stickyHeaderEnabled }" role="row">
        <div v-if="expandable" class="grid-header-cell grid-expand-cell" :style="expanderStyle" />
        <div v-if="config.checkboxEnabled" class="grid-header-cell" :style="selectionStyle"><input type="checkbox" :checked="state.rows.some(row => row._isChecked)" :disabled="config.isCheckboxHeaderDisabled?.(grid)" :aria-label="msg.selectAll" @change="grid.toggleAll(($event.target as HTMLInputElement).checked)" /></div>
        <div v-if="config.radioButtonSelectionEnabled" class="grid-header-cell" :style="selectionStyle" />
        <div v-for="column in columns" :key="column.name" class="grid-header-cell" :class="[alignmentClass(column, grid), { 'grid-header-order': config.orderByEnabled !== false && column.orderByEnabled !== false }]" :style="columnStyle(column, grid)" role="columnheader" @click="openSortMenu($event, column)">
          <RuntimeContent :value="headerValue(column)" /><span class="arcana-sort" aria-hidden="true">{{ sortMark(column) }}</span>
        </div>
        <div v-if="config.actions" class="grid-header-cell" :style="actionStyle(grid)">{{ msg.actions }}</div>
      </div>
      <div v-if="config.searchEnabled !== false" class="grid-search-row" role="row">
        <div v-if="expandable" class="grid-search-row-cell grid-expand-cell" :style="expanderStyle" />
        <div v-if="config.checkboxEnabled" class="grid-search-row-cell" :style="selectionStyle" /><div v-if="config.radioButtonSelectionEnabled" class="grid-search-row-cell" :style="selectionStyle" />
        <div v-for="column in columns" :key="column.name" class="grid-search-row-cell" :style="columnStyle(column, grid)">
          <RuntimeContent v-if="column.searchType === 'COMPONENT'" :value="column.searchTypeRenderer?.()" />
          <FilterField v-else-if="searchable(column)" :column="column" :model-value="state.filters[column.filterName ?? column.name] ?? config.initialFilters?.[column.filterName ?? column.name]" :disabled="disabledFilter(column)" :messages="msg" :locale="gridLocale" @change="grid.applyFilter(column, $event)" />
        </div>
        <div v-if="config.actions" class="grid-search-row-cell" :style="actionStyle(grid)" />
      </div>
      <div class="grid-body" role="rowgroup">
        <div v-if="state.loading && state.rows.length === 0" class="arcana-grid-status" role="status">{{ msg.loading }}</div>
        <div v-else-if="state.rows.length === 0" class="arcana-grid-status">{{ msg.empty }}</div>
        <template v-for="row in state.rows" :key="row._uuid">
          <div class="grid-row flex" :class="{ 'grid-row-focused': row._hasFocus || focusedRow === row._uuid, 'grid-row-checked': row._isChecked || row._isRadioChecked }" role="row" @click="onRow(row)" @dblclick="config.onDoubleClickRow?.(row, grid)">
            <div v-if="expandable" class="grid-cell grid-expand-cell spark-grid-selection-cell" data-label="" :style="expanderStyle"><button type="button" class="grid-expand-toggle" :class="{ 'is-open': isExpanded(row) }" :aria-expanded="isExpanded(row)" :aria-label="isExpanded(row) ? msg.collapseRow : msg.expandRow" @click="onExpandToggle($event, row)"><svg viewBox="0 0 16 16" aria-hidden="true"><path d="M6 4l4 4-4 4" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" /></svg></button></div>
            <div v-if="config.checkboxEnabled" class="grid-cell spark-grid-selection-cell" :style="selectionCellStyle(row)"><input type="checkbox" :checked="row._isChecked" :disabled="row._isCheckboxDisabled" :aria-label="msg.selectRow" @click.stop @change="grid.toggleRow(row, ($event.target as HTMLInputElement).checked)" /></div>
            <div v-if="config.radioButtonSelectionEnabled" class="grid-cell spark-grid-selection-cell" :style="selectionCellStyle(row)"><input type="radio" :name="state.uuid" :checked="row._isRadioChecked" :aria-label="msg.selectRow" @click.stop @change="selectRadio(row)" /></div>
            <div v-for="column in columns" :key="column.name" class="grid-cell" :class="[alignmentClass(column, grid), { 'grid-cell-focused': focusedCell === `${row._uuid}:${column.name}` }]" :data-label="column.label" :style="cellStyle(column, row)" role="cell" @click="onCell(column, row)" @dblclick="config.onDoubleClickCell?.(grid.getCellValue(column, row), column, row, grid)" @contextmenu="context($event, column, row)"><RuntimeContent :value="grid.getCellValue(column, row)" /></div>
            <div v-if="config.actions" class="grid-cell" :data-label="msg.actions" :style="actionStyle(grid)"><template v-for="(action, index) in config.actions" :key="index"><RuntimeContent v-if="action.isVisible?.(row) ?? true" :value="action.element(row)" /></template></div>
          </div>
          <div v-if="expandable && isExpanded(row)" class="grid-detail-row" role="row"><div class="grid-detail-cell" role="cell"><ExpandedRowContent :row="row" /></div></div>
        </template>
      </div>
      <div v-if="config.footerSummarizerEnabled" class="grid-summarizer" :class="{ 'grid-summarizer-sticky': config.stickyHeaderEnabled }">
        <div v-if="expandable" class="grid-summarizer-cell grid-expand-cell" :style="expanderStyle" />
        <div v-if="config.checkboxEnabled" class="grid-summarizer-cell" :style="selectionStyle" /><div v-if="config.radioButtonSelectionEnabled" class="grid-summarizer-cell" :style="selectionStyle" />
        <div v-for="column in columns" :key="column.name" class="grid-summarizer-cell" :class="alignmentClass(column, grid)" :style="{ ...columnStyle(column, grid), padding: '8px 10px' }"><RuntimeContent :value="grid.getSummarizedValue(column)?.formatted" /></div>
        <div v-if="config.actions" class="grid-summarizer-cell" :style="actionStyle(grid)" />
      </div>
    </div>
    <div v-if="config.footerVisible ?? true" class="grid-footer">
      <div class="spark-grid-pages">
        <label v-if="config.isRowsPerPageVisible ?? true" class="spark-grid__per-page">{{ msg.perPage }} <select :value="state.rowsPerPage" class="spark-grid-datatable-select" @change="grid.paginate(1, Number(($event.target as HTMLSelectElement).value))"><option v-for="size in [10,25,50,100,250,500]" :key="size" :value="size">{{ size }}</option></select></label>
        <span v-if="state.totalRows" class="spark-grid__info">{{ formatMessage(msg.showingRange, { from: beginning, to: ending, total: state.totalRows }) }}</span>
        <div class="spark-grid__pagination-group">
          <span class="spark-grid-selected-rows">{{ grid.getCheckedRows().length ? formatMessage(msg.selectedCount, { count: grid.getCheckedRows().length }) : '' }}</span>
          <ul :aria-label="msg.pagination"><li><button type="button" :disabled="state.currentPage <= 1" :aria-label="msg.previousPage" @click="grid.paginate(state.currentPage - 1, state.rowsPerPage)">‹</button></li><li v-for="page in pages" :key="page" :class="{ current: page === state.currentPage }"><button type="button" :disabled="page === state.currentPage" @click="grid.paginate(page, state.rowsPerPage)">{{ page }}</button></li><li><button type="button" :disabled="state.currentPage >= lastPage" :aria-label="msg.nextPage" @click="grid.paginate(state.currentPage + 1, state.rowsPerPage)">›</button></li></ul>
        </div>
      </div>
    </div>
    <div v-if="menu" class="arcana-context-menu" :class="themeClass" :style="{ left: `${menu.x}px`, top: `${menu.y}px` }" role="menu" @click.stop><button v-for="(item, index) in menu.items" :key="`${item.label}-${index}`" type="button" role="menuitem" @click="item.onClick?.(); menu = null">{{ item.label }}</button></div>
    <div v-if="sortMenu" class="arcana-context-menu arcana-sort-menu" :class="themeClass" :style="{ left: `${sortMenu.x}px`, top: `${sortMenu.y}px` }" role="menu" :aria-label="msg.sortMenu" @click.stop>
      <button type="button" role="menuitem" :class="{ 'is-active': state.orderBy?.name === sortMenu.name && state.orderBy.direction === 'asc' }" @click="applySortOption('asc')"><svg viewBox="0 0 16 16" aria-hidden="true"><path d="M8 3.5 3.5 8h3v4.5h3V8h3L8 3.5Z" /></svg>{{ msg.sortAscending }}</button>
      <button type="button" role="menuitem" :class="{ 'is-active': state.orderBy?.name === sortMenu.name && state.orderBy.direction === 'desc' }" @click="applySortOption('desc')"><svg viewBox="0 0 16 16" aria-hidden="true"><path d="M8 12.5 12.5 8h-3V3.5h-3V8h-3L8 12.5Z" /></svg>{{ msg.sortDescending }}</button>
      <button v-if="state.orderBy?.name === sortMenu.name" type="button" role="menuitem" class="arcana-sort-menu__clear" @click="applySortOption(null)"><svg viewBox="0 0 16 16" aria-hidden="true"><path d="M4 4l8 8M12 4l-8 8" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" /></svg>{{ msg.sortClear }}</button>
    </div>
  </div>
</template>

// src/svelte/ArcanaDataTable.svelte
<script lang="ts">
  /**
   * `ArcanaDataTable` — Svelte 5 adapter over the framework-agnostic
   * controller (`core/controller.ts`). Markup, classes and behavior mirror
   * the React/Vue adapters 1:1: header with the sort menu, filter row,
   * checkbox/radio selection, actions, context menu, footer with pagination,
   * summarizer, themes and expandable rows.
   *
   * Custom content (`valueGetter`, `actions[].element`, `expandedRowRenderer`,
   * …) accepts what `Renderable` allows in a framework-neutral way: HTML
   * strings, numbers/booleans, DOM nodes or callbacks returning any of those.
   */
  import { createDataTable } from "../core/controller";
  import { formatMessage, resolveArcanaLocale, resolveArcanaMessages } from "../core/locale";
  import { arcanaThemeClass } from "../core/theme";
  import { actionStyle, alignmentClass, columnStyle, expanderStyle, inlineStyle, pagination, selectionStyle } from "../core/view";
  import type { ContextMenuItem, DataTableApi, DataTableColumn, DataTableConfig, DataTableRow, OrderBy } from "../core/types";
  import Content from "./Content.svelte";
  import ExpandedRowContent from "./ExpandedRowContent.svelte";
  import FilterField from "./FilterField.svelte";
  import "../assets/SparkGrid.css";

  let { config, class: className = "", onMounted }: {
    config: DataTableConfig<DataTableRow>;
    class?: string;
    onMounted?: (grid: DataTableApi<DataTableRow>) => void;
  } = $props();

  let grid = $state.raw<DataTableApi<DataTableRow>>(createDataTable(config));
  let snap = $state.raw(grid.getSnapshot());
  let menu = $state.raw<{ x: number; y: number; items: ContextMenuItem[] } | null>(null);
  let sortMenu = $state.raw<{ x: number; y: number; name: string } | null>(null);
  let focusedRow = $state<string | null>(null);
  let focusedCell = $state<string | null>(null);

  let mountedConfig: DataTableConfig<DataTableRow> | null = null;
  $effect(() => {
    if (mountedConfig && mountedConfig !== config) grid = createDataTable(config);
    mountedConfig = config;
    const instance = grid;
    snap = instance.getSnapshot();
    const unsubscribe = instance.subscribe(() => { snap = instance.getSnapshot(); });
    onMounted?.(instance);
    if (config.sendRequestOnMounted !== false) void instance.refresh();
    return unsubscribe;
  });

  $effect(() => {
    if (!menu && !sortMenu) return;
    const close = () => { menu = null; sortMenu = null; };
    const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") close(); };
    window.addEventListener("click", close);
    window.addEventListener("blur", close);
    window.addEventListener("keydown", onKey);
    return () => {
      window.removeEventListener("click", close);
      window.removeEventListener("blur", close);
      window.removeEventListener("keydown", onKey);
    };
  });

  const themeClass = $derived(arcanaThemeClass(config.theme));
  const msg = $derived(resolveArcanaMessages(config));
  const gridLocale = $derived(resolveArcanaLocale(config));
  const columns = $derived.by(() => { snap; return grid.getColumns(); });
  const pages = $derived(pagination(snap.currentPage, snap.totalRows, snap.rowsPerPage));
  const lastPage = $derived(Math.ceil(snap.totalRows / snap.rowsPerPage));
  const beginning = $derived(snap.totalRows ? ((snap.currentPage - 1) * snap.rowsPerPage) + 1 : 0);
  const ending = $derived(Math.min(snap.currentPage * snap.rowsPerPage, snap.totalRows));
  const expandable = $derived(Boolean(config.expandableRowsEnabled));

  const searchableColumn = (column: DataTableColumn<DataTableRow>) => column.searchEnabled ?? true;
  const disabledFilter = (column: DataTableColumn<DataTableRow>) => Boolean(config.disableFilterWhenPresentOnInitialFilters && config.initialFilters?.[column.filterName ?? column.name]);
  const filterValue = (column: DataTableColumn<DataTableRow>) => snap.filters[column.filterName ?? column.name] ?? config.initialFilters?.[column.filterName ?? column.name];

  const cellStyle = (column: DataTableColumn<DataTableRow>, row: DataTableRow) => inlineStyle(
    columnStyle(column, grid),
    { padding: "8px 10px" },
    config.onBeforeCellStyleMounted?.(grid.getCellValue(column, row), column, row, grid),
    column.onBeforeColumnStyleMounted?.(grid.getCellValue(column, row), row, grid)
  );
  const selectionCellStyle = (row: DataTableRow) => inlineStyle(selectionStyle, config.onBeforeCheckboxAndRadioButtonStyleMounted?.(row, grid));

  function openSortMenu(event: MouseEvent, column: DataTableColumn<DataTableRow>) {
    if (config.orderByEnabled === false || column.orderByEnabled === false) return;
    const name = column.filterName ?? column.name;
    event.stopPropagation();
    const rect = (event.currentTarget as HTMLElement).getBoundingClientRect();
    sortMenu = sortMenu?.name === name ? null : { x: rect.left, y: rect.bottom + 2, name };
  }

  function applySortOption(direction: OrderBy["direction"] | null) {
    if (!sortMenu) return;
    void grid.applyOrderBy(direction ? { name: sortMenu.name, direction } : null);
    sortMenu = null;
  }

  const sortMark = (column: DataTableColumn<DataTableRow>) => snap.orderBy?.name !== (column.filterName ?? column.name) ? "↕" : snap.orderBy.direction === "asc" ? "↑" : "↓";
  const headerValue = (column: DataTableColumn<DataTableRow>) => {
    const initial = config.onBeforeHeaderCellMounted?.(column, grid);
    return column.headerContentGetter?.(initial, grid) ?? initial ?? column.label;
  };

  function openMenu(event: MouseEvent, column: DataTableColumn<DataTableRow>, row: DataTableRow) {
    const items = config.onContextMenu?.(grid.getCellValue(column, row), column, row, grid);
    if (items?.length) { event.preventDefault(); menu = { x: event.clientX, y: event.clientY, items }; }
  }

  const isExpanded = (row: DataTableRow) => Boolean(row._uuid && snap.expandedRowUuids.includes(row._uuid));
  function toggleExpand(row: DataTableRow) {
    if (!row._uuid) return;
    isExpanded(row) ? grid.collapseRow(row._uuid) : grid.expandRow(row._uuid);
  }
  function onExpandToggle(event: MouseEvent, row: DataTableRow) {
    event.stopPropagation();
    toggleExpand(row);
  }

  function selectRow(row: DataTableRow) {
    if (config.rowFocusEnabled) focusedRow = row._uuid ?? null;
    if (expandable && config.expandRowOnClick) toggleExpand(row);
    config.onClickRow?.(row, grid);
  }

  function selectCell(column: DataTableColumn<DataTableRow>, row: DataTableRow) {
    if (config.cellFocusEnabled ?? true) focusedCell = `${row._uuid}:${column.name}`;
    config.onClickCell?.(grid.getCellValue(column, row), column, row, grid);
  }

  // Imperative API — mirrors the Vue `defineExpose` surface; available on the
  // component instance (`bind:this` / `mount()` exports).
  export function getApi() { return grid; }
  export function refresh() { return grid.refresh(); }
  export function fetch() { return grid.fetch(); }
  export function setRows(rows: DataTableRow[]) { return grid.setRows(rows); }
  export function setDataset(rows: DataTableRow[]) { return grid.setDataset(rows); }
  export function getDataset() { return grid.getDataset(); }
  export function clearRows() { grid.clearRows(); }
  export function addRow(row: DataTableRow) { grid.addRow(row); }
  export function removeRow(uuid: string) { grid.removeRow(uuid); }
  export function updateRow(uuid: string, row: Partial<DataTableRow>) { grid.updateRow(uuid, row); }
  export function upsert(uuid: string, row: DataTableRow) { grid.upsert(uuid, row); }
  export function getRows() { return grid.getRows(); }
  export function getCheckedRows() { return grid.getCheckedRows(); }
  export function clearCheckedRows() { grid.clearCheckedRows(); }
  export function setFilter(name: string, value: unknown) { return grid.setFilter(name, value); }
  export function setFilters(filters: Record<string, unknown>) { return grid.setFilters(filters); }
  export function expandRow(uuid: string) { grid.expandRow(uuid); }
  export function collapseRow(uuid: string) { grid.collapseRow(uuid); }
  export function getExpandedRows() { return grid.getExpandedRows(); }
</script>

<div class={`spark-grid grid-wrapper ${themeClass} ${config.responsiveMode === "VERTICAL_RECORD" ? "spark-grid-responsive-vertical" : ""} ${className}`.trim()} aria-label={config.ariaLabel ?? msg.gridLabel} aria-busy={snap.loading}>
  {#if snap.error}<div class="arcana-grid-error" role="alert">{msg.loadError}</div>{/if}
  <div class="spark-grid-body" style={config.overflowEnabled ? `max-height: ${config.height ?? 560}px; overflow: auto` : undefined}>
    <div class={`grid-header ${config.stickyHeaderEnabled ? "grid-header-sticky" : ""}`} role="row">
      {#if expandable}<div class="grid-header-cell grid-expand-cell" style={inlineStyle(expanderStyle)}></div>{/if}
      {#if config.checkboxEnabled}<div class="grid-header-cell" style={inlineStyle(selectionStyle)}><input type="checkbox" checked={snap.rows.some((row) => row._isChecked)} disabled={config.isCheckboxHeaderDisabled?.(grid)} aria-label={msg.selectAll} onchange={(event) => grid.toggleAll((event.currentTarget as HTMLInputElement).checked)} /></div>{/if}
      {#if config.radioButtonSelectionEnabled}<div class="grid-header-cell" style={inlineStyle(selectionStyle)}></div>{/if}
      {#each columns as column (column.name)}
        <div class={`grid-header-cell ${alignmentClass(column, grid)} ${config.orderByEnabled !== false && column.orderByEnabled !== false ? "grid-header-order" : ""}`} style={inlineStyle(columnStyle(column, grid))} role="columnheader" onclick={(event) => openSortMenu(event, column)}><Content value={headerValue(column)} /><span class="arcana-sort" aria-hidden="true">{sortMark(column)}</span></div>
      {/each}
      {#if config.actions}<div class="grid-header-cell" style={inlineStyle(actionStyle(grid))}>{msg.actions}</div>{/if}
    </div>
    {#if config.searchEnabled !== false}
      <div class="grid-search-row" role="row">
        {#if expandable}<div class="grid-search-row-cell grid-expand-cell" style={inlineStyle(expanderStyle)}></div>{/if}
        {#if config.checkboxEnabled}<div class="grid-search-row-cell" style={inlineStyle(selectionStyle)}></div>{/if}{#if config.radioButtonSelectionEnabled}<div class="grid-search-row-cell" style={inlineStyle(selectionStyle)}></div>{/if}
        {#each columns as column (column.name)}
          <div class="grid-search-row-cell" style={inlineStyle(columnStyle(column, grid))}>
            {#if column.searchType === "COMPONENT"}
              <Content value={column.searchTypeRenderer?.()} />
            {:else if searchableColumn(column)}
              <FilterField {column} value={filterValue(column)} disabled={disabledFilter(column)} messages={msg} locale={gridLocale} onChange={(value) => void grid.applyFilter(column, value)} />
            {/if}
          </div>
        {/each}
        {#if config.actions}<div class="grid-search-row-cell" style={inlineStyle(actionStyle(grid))}></div>{/if}
      </div>
    {/if}
    <div class="grid-body" role="rowgroup">
      {#if snap.loading && !snap.rows.length}
        <div class="arcana-grid-status" role="status">{msg.loading}</div>
      {:else if !snap.rows.length}
        <div class="arcana-grid-status">{msg.empty}</div>
      {/if}
      {#each snap.rows as row (row._uuid)}
        <div class={`grid-row flex ${row._hasFocus || focusedRow === row._uuid ? "grid-row-focused" : ""} ${row._isChecked || row._isRadioChecked ? "grid-row-checked" : ""}`} role="row" onclick={() => selectRow(row)} ondblclick={() => config.onDoubleClickRow?.(row, grid)}>
          {#if expandable}<div class="grid-cell grid-expand-cell spark-grid-selection-cell" data-label="" style={inlineStyle(expanderStyle)}><button type="button" class={`grid-expand-toggle${isExpanded(row) ? " is-open" : ""}`} aria-expanded={isExpanded(row)} aria-label={isExpanded(row) ? msg.collapseRow : msg.expandRow} onclick={(event) => onExpandToggle(event, row)}><svg viewBox="0 0 16 16" aria-hidden="true"><path d="M6 4l4 4-4 4" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" /></svg></button></div>{/if}
          {#if config.checkboxEnabled}<div class="grid-cell spark-grid-selection-cell" style={selectionCellStyle(row)}><input type="checkbox" checked={Boolean(row._isChecked)} disabled={row._isCheckboxDisabled} aria-label={msg.selectRow} onclick={(event) => event.stopPropagation()} onchange={(event) => grid.toggleRow(row, (event.currentTarget as HTMLInputElement).checked)} /></div>{/if}
          {#if config.radioButtonSelectionEnabled}<div class="grid-cell spark-grid-selection-cell" style={selectionCellStyle(row)}><input type="radio" name={snap.uuid} checked={Boolean(row._isRadioChecked)} aria-label={msg.selectRow} onclick={(event) => event.stopPropagation()} onchange={() => grid.setSelectedRadioRow(row)} /></div>{/if}
          {#each columns as column (column.name)}
            <div class={`grid-cell ${alignmentClass(column, grid)} ${focusedCell === `${row._uuid}:${column.name}` ? "grid-cell-focused" : ""}`} data-label={column.label} style={cellStyle(column, row)} role="cell" onclick={() => selectCell(column, row)} ondblclick={() => config.onDoubleClickCell?.(grid.getCellValue(column, row), column, row, grid)} oncontextmenu={(event) => openMenu(event, column, row)}><Content value={grid.getCellValue(column, row)} /></div>
          {/each}
          {#if config.actions}
            <div class="grid-cell" data-label={msg.actions} style={inlineStyle(actionStyle(grid))}>
              {#each config.actions as action, index (index)}
                {#if action.isVisible?.(row) ?? true}<Content value={action.element(row)} />{/if}
              {/each}
            </div>
          {/if}
        </div>
        {#if expandable && isExpanded(row)}
          <div class="grid-detail-row" role="row"><div class="grid-detail-cell" role="cell"><ExpandedRowContent {row} {grid} /></div></div>
        {/if}
      {/each}
    </div>
    {#if config.footerSummarizerEnabled}
      <div class={`grid-summarizer ${config.stickyHeaderEnabled ? "grid-summarizer-sticky" : ""}`}>
        {#if expandable}<div class="grid-summarizer-cell grid-expand-cell" style={inlineStyle(expanderStyle)}></div>{/if}
        {#if config.checkboxEnabled}<div class="grid-summarizer-cell" style={inlineStyle(selectionStyle)}></div>{/if}{#if config.radioButtonSelectionEnabled}<div class="grid-summarizer-cell" style={inlineStyle(selectionStyle)}></div>{/if}
        {#each columns as column (column.name)}
          <div class={`grid-summarizer-cell ${alignmentClass(column, grid)}`} style={inlineStyle(columnStyle(column, grid), { padding: "8px 10px" })}><Content value={grid.getSummarizedValue(column)?.formatted} /></div>
        {/each}
        {#if config.actions}<div class="grid-summarizer-cell" style={inlineStyle(actionStyle(grid))}></div>{/if}
      </div>
    {/if}
  </div>
  {#if config.footerVisible ?? true}
    <div class="grid-footer"><div class="spark-grid-pages">
      {#if config.isRowsPerPageVisible ?? true}
        <label class="spark-grid__per-page">{msg.perPage} <select value={snap.rowsPerPage} class="spark-grid-datatable-select" onchange={(event) => void grid.paginate(1, Number((event.currentTarget as HTMLSelectElement).value))}>{#each [10, 25, 50, 100, 250, 500] as size (size)}<option value={size}>{size}</option>{/each}</select></label>
      {/if}
      {#if snap.totalRows}<span class="spark-grid__info">{formatMessage(msg.showingRange, { from: beginning, to: ending, total: snap.totalRows })}</span>{/if}
      <div class="spark-grid__pagination-group"><span class="spark-grid-selected-rows">{grid.getCheckedRows().length ? formatMessage(msg.selectedCount, { count: grid.getCheckedRows().length }) : ""}</span>
        <ul aria-label={msg.pagination}><li><button type="button" disabled={snap.currentPage <= 1} aria-label={msg.previousPage} onclick={() => void grid.paginate(snap.currentPage - 1, snap.rowsPerPage)}>‹</button></li>{#each pages as page (page)}<li class={page === snap.currentPage ? "current" : ""}><button type="button" disabled={page === snap.currentPage} onclick={() => void grid.paginate(page, snap.rowsPerPage)}>{page}</button></li>{/each}<li><button type="button" disabled={snap.currentPage >= lastPage} aria-label={msg.nextPage} onclick={() => void grid.paginate(snap.currentPage + 1, snap.rowsPerPage)}>›</button></li></ul>
      </div>
    </div></div>
  {/if}
  {#if menu}
    <div class={`arcana-context-menu ${themeClass}`} style={`left: ${menu.x}px; top: ${menu.y}px`} role="menu" onclick={(event) => event.stopPropagation()}>
      {#each menu.items as item, index (`${item.label}-${index}`)}
        <button type="button" role="menuitem" onclick={() => { item.onClick?.(); menu = null; }}>{item.label}</button>
      {/each}
    </div>
  {/if}
  {#if sortMenu}
    <div class={`arcana-context-menu arcana-sort-menu ${themeClass}`} style={`left: ${sortMenu.x}px; top: ${sortMenu.y}px`} role="menu" aria-label={msg.sortMenu} onclick={(event) => event.stopPropagation()}>
      <button type="button" role="menuitem" class={snap.orderBy?.name === sortMenu.name && snap.orderBy.direction === "asc" ? "is-active" : ""} onclick={() => applySortOption("asc")}><svg viewBox="0 0 16 16" aria-hidden="true"><path d="M8 3.5 3.5 8h3v4.5h3V8h3L8 3.5Z" /></svg>{msg.sortAscending}</button>
      <button type="button" role="menuitem" class={snap.orderBy?.name === sortMenu.name && snap.orderBy.direction === "desc" ? "is-active" : ""} onclick={() => applySortOption("desc")}><svg viewBox="0 0 16 16" aria-hidden="true"><path d="M8 12.5 12.5 8h-3V3.5h-3V8h-3L8 12.5Z" /></svg>{msg.sortDescending}</button>
      {#if snap.orderBy?.name === sortMenu.name}
        <button type="button" role="menuitem" class="arcana-sort-menu__clear" onclick={() => applySortOption(null)}><svg viewBox="0 0 16 16" aria-hidden="true"><path d="M4 4l8 8M12 4l-8 8" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" /></svg>{msg.sortClear}</button>
      {/if}
    </div>
  {/if}
</div>
